Added tokens to simplify compiling for 45/46 keys.
An attempt to make it easy to switch on a #define between
various hardware configurations (44, 45, 46 keys) failed.
This: #define J1 , KC_A // seems to have failed to be
recognized as a key definition.
error: error: macro "LAYOUT_command" requires 45 arguments, but only 44 given

Left in are some code tokens (J1-J4) and #defines that need
at least bulk replacement in keymap.c and optionally qwerty_dvorak.c,
to compile for such hardware configurations. It would be nice
if this could be done better.