changes made to 5x7_5 due to failing build checks
## failing build check
```
Compiling: quantum/keymap_introspection.c                                                          In file included from quantum/keymap_introspection.c:5:
./keyboards/handwired/dactyl_manuform/5x7_5/keymaps/default/keymap.c:41:5: error: macro "LAYOUT_5x7_5" requires 72 arguments, but only 71 given
     ),
     ^
In file included from quantum/keymap_introspection.c:5:
./keyboards/handwired/dactyl_manuform/5x7_5/keymaps/default/keymap.c:34:17: error: 'LAYOUT_5x7_5' undeclared here (not in a function)
     [_QWERTY] = LAYOUT_5x7_5(
                 ^~~~~~~~~~~~
 [ERRORS]
 |
 |
 |
gmake[1]: *** [builddefs/common_rules.mk:357: .build/obj_handwired_dactyl_manuform_5x7_5_default/quantum/keymap_introspection.o] Error 1
```