Update `OLED_FONT_H`
Update to fix a compilation error caused by changing the "vendor"
directory on the initial bring-up. (Source repository uses
`keyboards/keyball/`, but this branch uses `keyboards/yowkees/`.)

```
Compiling: drivers/oled/oled_driver.c                                                              drivers/oled/oled_driver.c:27:21: fatal error: keyboards/keyball/lib/logofont/logofont.c: No such file or directory
compilation terminated.
 [ERRORS]
 |
 |
 |
gmake: *** [builddefs/common_rules.mk:373: .build/obj_yowkees_keyball39_default/oled_driver.o] Error 1
gmake: *** Waiting for unfinished jobs....
```