Fix timer.h vs Timer.h case issue on OS X
On case insensitive filesytems, Timer.h is found instead of timer.h.
That causes problems if you don't have a full C++ toolchain:

```
In file included from ../../tmk_core/tool/mbed/mbed-sdk/libraries/mbed/api/timer.h:19:0,
                 from matrix.c:4:
../../tmk_core/tool/mbed/mbed-sdk/libraries/mbed/api/platform.h:25:19: fatal error: cstddef: No such file or directory
 #include <cstddef>
                   ^
compilation terminated.
make: *** [build/matrix.o] Error 1
```

This works around the issue by renaming the header to clearly indicate
that it is a C++ include

See https://github.com/tmk/tmk_keyboard/issues/212 for some details on
this.